source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.com/TahaElsheikh1/specs.git'

use_frameworks!

target 'VUIComponents-Swift_Example' do
  pod 'VUIComponents-Swift', :path => '../'

  target 'VUIComponents-Swift_Tests' do
    inherit! :search_paths
    
  end
end
